version: '2'

services:
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  app:
    image: 'mohamed3laa/python'
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
volumes:
  redis_data:
    driver: local

