pipeline {
  agent any
  stages {
    stage('SCM') {
      steps {
        echo "Build Preparation"
        cleanWs()
        checkout scm
      }
    }
    stage('Run Unit Test and Lint'){
      steps{
        script{
          if (env.BRANCH_NAME.equals('master')){
            echo   "This is Unit Test and Linting Stage"
            sh """
              echo "Unit testing and Liniting Commands"
              cd ${WORKSPACE}/DevOps-challenge
              python3 tests/test.py
            """
          }
        }
      }
    }
    stage('Build if branch eq to master'){
      steps {
        script{
          if (env.BRANCH_NAME.equals('addjenkinsfile')){
              withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
            sh """
              cd ${WORKSPACE}/DevOps-challenge
              docker login --username $USERNAME --password $PASSWORD 
              docker tag mohamed3laa/python  mohamed3laa/python:${BUILD_NUMBER}
              docker push mohamed3laa/python:${BUILD_NUMBER}
              docker build  -t mohamed3laa/python . 
              docker push mohamed3laa/python
            """
          }
        }  
      }
    }
  }  
    stage('Deploy to Development Env or Production'){
      steps {
        script{
          if (env.BRANCH_NAME.equals('development') || env.BRANCH_NAME.equals('production') || env.BRANCH_NAME.equals('addjenkinsfile')){
            echo "Deployment stage"
            sh """
              cd ${WORKSPACE}/DevOps-challenge
      	      sed -i s/BranchName/${BRANCH_NAME}/ Deployment/deploy.yaml
	      for f in app.yaml  namespaces.yaml  redis.yaml
	      do
              sed -i s/BranchName/${BRANCH_NAME}/ K8sDeployment/${f}               
              done
            """
          }
        }
      }
    }
  }
}
